"""empty message

Revision ID: 226ff711ec60
Revises: None
Create Date: 2014-06-26 20:27:53.507137

"""

# revision identifiers, used by Alembic.
revision = '226ff711ec60'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=128), nullable=True))
    op.drop_column('user', u'username')
    op.drop_column('user', u'lastname')
    op.drop_column('user', u'picture_url')
    op.drop_column('user', u'email')
    op.drop_column('user', u'firstname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(u'firstname', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column(u'email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column(u'picture_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column(u'lastname', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column(u'username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('user', 'name')
    ### end Alembic commands ###
