"""empty message

Revision ID: 3026b51c6d3f
Revises: 3f4722f2fe1e
Create Date: 2014-06-30 00:44:09.549869

"""

# revision identifiers, used by Alembic.
revision = '3026b51c6d3f'
down_revision = '3f4722f2fe1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poem_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('password', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'password')
    op.drop_table('comment')
    ### end Alembic commands ###
