"""empty message

Revision ID: 43dc93744ecf
Revises: 3026b51c6d3f
Create Date: 2014-06-30 00:51:03.572722

"""

# revision identifiers, used by Alembic.
revision = '43dc93744ecf'
down_revision = '3026b51c6d3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
