"""empty message

Revision ID: da20a036d4d
Revises: 226ff711ec60
Create Date: 2014-06-26 20:30:22.873277

"""

# revision identifiers, used by Alembic.
revision = 'da20a036d4d'
down_revision = '226ff711ec60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'user',
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('user_id_seq'::regclass)", nullable=False),
    sa.Column(u'name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'user_pkey')
    )
    ### end Alembic commands ###
