"""empty message

Revision ID: fb6ba7e4778
Revises: 43dc93744ecf
Create Date: 2014-06-30 00:52:47.581060

"""

# revision identifiers, used by Alembic.
revision = 'fb6ba7e4778'
down_revision = '43dc93744ecf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
